name: maps
channels:
    - ioos
dependencies:
    - python=3.4
    - jupyter
    - basemap
    - cartopy
    - mplleaflet
    - folium
    - bokeh
    - seawater
    - gpxpy
    - oceans
    - geopandas
